modLoader="javafml"
loaderVersion="[45,)"
license="MIT License"

[[mods]]
modId="elec_tronics"
version="0.0.1"
displayName="Electronics"
credits="SirJStig, Mewbster9900"
displayURL="https://github.com/SirStig/Elec_tronics"
logoFile="logo.png"
authors="SirJStig"
description="Elec Tronics is a mod based around your favorite mods with a bit of a touch of realism"

[[dependencies.elec_tronics]]
    modId="minecraft"
    mandatory=true
    versionRange="[1.19.4]"
    ordering="NONE"
    side="BOTH"




