modLoader="javafml"
loaderVersion="[37,)"
license="MIT License"

[[mods]]
modId="elec_tronics"
version="0.0.0.1"
displayName="Elec Tronics"
credits="SirJStig, Mewbster9900"
displayURL="https://github.com/SirStig/Elec_tronics"
updateJSONURL="https://raw.githubusercontent.com/SirStig/Elec_tronics/1.17.x(Prototype)/update.json"
logoFile="logo.png"
authors="SirJStig"
description='''
Elec Tronics is a mod based around your favorite mods with a bit of a touch of realism
'''

[[dependencies.elec_tronics]]
    modId="minecraft"
    mandatory=true
    versionRange="[1.17.1]"
    ordering="NONE"
    side="BOTH"




