
/*
 *    MCreator note: This file will be REGENERATED on each build.
 */
package net.elec_tronics.init;

import net.minecraftforge.registries.RegistryObject;
import net.minecraftforge.registries.ForgeRegistries;
import net.minecraftforge.registries.DeferredRegister;

import net.minecraft.world.level.block.Block;

import net.elec_tronics.block.WaterturbinemachineBlock;
import net.elec_tronics.block.UraniumoreBlock;
import net.elec_tronics.block.TungstenBlock;
import net.elec_tronics.block.Tankfullhalf1Block;
import net.elec_tronics.block.Tankfull9Block;
import net.elec_tronics.block.Tankfull8Block;
import net.elec_tronics.block.Tankfull7Block;
import net.elec_tronics.block.Tankfull6Block;
import net.elec_tronics.block.Tankfull5Block;
import net.elec_tronics.block.Tankfull4Block;
import net.elec_tronics.block.Tankfull3Block;
import net.elec_tronics.block.Tankfull2Block;
import net.elec_tronics.block.Tankfull1Block;
import net.elec_tronics.block.Tankfull14Block;
import net.elec_tronics.block.Tankfull13Block;
import net.elec_tronics.block.Tankfull12Block;
import net.elec_tronics.block.Tankfull11Block;
import net.elec_tronics.block.Tankfull10Block;
import net.elec_tronics.block.TankBlock;
import net.elec_tronics.block.T1WireBlock;
import net.elec_tronics.block.SolarpaneltoprBlock;
import net.elec_tronics.block.SolarpaneltopBlock;
import net.elec_tronics.block.SolarPanelrBlock;
import net.elec_tronics.block.SolarPanelT1Block;
import net.elec_tronics.block.RockSaltBlock;
import net.elec_tronics.block.ReinforcedblastbrickBlock;
import net.elec_tronics.block.RefineryT1Block;
import net.elec_tronics.block.RefinedOilBlock;
import net.elec_tronics.block.QuarryT1Block;
import net.elec_tronics.block.PipeupangleBlock;
import net.elec_tronics.block.PipeupBlock;
import net.elec_tronics.block.PipetdownandupBlock;
import net.elec_tronics.block.PipetdownBlock;
import net.elec_tronics.block.PipetBlock;
import net.elec_tronics.block.PipestraightBlock;
import net.elec_tronics.block.PipejunctionupanddownstraightBlock;
import net.elec_tronics.block.PipejunctionupanddownBlock;
import net.elec_tronics.block.Pipejunctionupanddown2Block;
import net.elec_tronics.block.PipejunctionupBlock;
import net.elec_tronics.block.Pipejunctionup2Block;
import net.elec_tronics.block.PipejunctionmainBlock;
import net.elec_tronics.block.PipejunctiondownBlock;
import net.elec_tronics.block.Pipejunctiondown2Block;
import net.elec_tronics.block.PipejunctionBlock;
import net.elec_tronics.block.PipehalfBlock;
import net.elec_tronics.block.PipedownangleBlock;
import net.elec_tronics.block.PipeanlgeupBlock;
import net.elec_tronics.block.PipeangledownBlock;
import net.elec_tronics.block.PipeangleBlock;
import net.elec_tronics.block.ManualFluidPumpdown2Block;
import net.elec_tronics.block.ManualFluidPumpBlock;
import net.elec_tronics.block.ManualFluidPump5Block;
import net.elec_tronics.block.ManualFluidPump4Block;
import net.elec_tronics.block.ManualFluidPump3Block;
import net.elec_tronics.block.HydrogenGasBlock;
import net.elec_tronics.block.ExtrusionMachineBlock;
import net.elec_tronics.block.EngineersworkbenchBlock;
import net.elec_tronics.block.EngineersWorkBenchTopSideBlock;
import net.elec_tronics.block.EngineersWorkBenchTopBlock;
import net.elec_tronics.block.EngineersWorkBenchSideBlock;
import net.elec_tronics.block.EnergyStorageT1Block;
import net.elec_tronics.block.ElectronicsoilBlock;
import net.elec_tronics.block.CrushermachineBlock;
import net.elec_tronics.block.Coolantt1Block;
import net.elec_tronics.block.CoalGeneratorMachineBlock;
import net.elec_tronics.block.ChlorineGasBlock;
import net.elec_tronics.block.CablehalfT1Block;
import net.elec_tronics.block.CableTUpandDownT1Block;
import net.elec_tronics.block.CableTUpT1Block;
import net.elec_tronics.block.CableTT1Block;
import net.elec_tronics.block.CableTDownT1Block;
import net.elec_tronics.block.CableJunctionUpandDownT1Block;
import net.elec_tronics.block.CableJunctionUpT1Block;
import net.elec_tronics.block.CableJunctionT1Block;
import net.elec_tronics.block.CableJunctionDownT1Block;
import net.elec_tronics.block.CableAngleT1Block;
import net.elec_tronics.block.BrineBlock;
import net.elec_tronics.block.BlastfurnancemachineBlock;
import net.elec_tronics.block.BauxiteOreBlock;
import net.elec_tronics.block.BauxiteBlockBlock;
import net.elec_tronics.block.Basewirecon5mainBlock;
import net.elec_tronics.block.Basewirecon5downBlock;
import net.elec_tronics.block.Basewirecon4upanddownstraightBlock;
import net.elec_tronics.block.Basewirecon4upanddownBlock;
import net.elec_tronics.block.Basewirecon4upBlock;
import net.elec_tronics.block.Basewirecon4downBlock;
import net.elec_tronics.block.Basewirecon3upangleBlock;
import net.elec_tronics.block.Basewirecon3upBlock;
import net.elec_tronics.block.Basewirecon3downangleBlock;
import net.elec_tronics.block.Basewirecon3downandupBlock;
import net.elec_tronics.block.Basewirecon3downBlock;
import net.elec_tronics.block.Basewirecon3Block;
import net.elec_tronics.block.Basewirecon2angleupBlock;
import net.elec_tronics.block.Basewirecon2angledownBlock;
import net.elec_tronics.block.Basewirecon2angleBlock;
import net.elec_tronics.block.BasepipeBlock;
import net.elec_tronics.block.BasecableT1Block;
import net.elec_tronics.ElecTronicsMod;

public class ElecTronicsModBlocks {
	public static final DeferredRegister<Block> REGISTRY = DeferredRegister.create(ForgeRegistries.BLOCKS, ElecTronicsMod.MODID);
	public static final RegistryObject<Block> URANIUMORE = REGISTRY.register("uraniumore", () -> new UraniumoreBlock());
	public static final RegistryObject<Block> TUNGSTEN = REGISTRY.register("tungsten", () -> new TungstenBlock());
	public static final RegistryObject<Block> REINFORCEDBLASTBRICK = REGISTRY.register("reinforcedblastbrick", () -> new ReinforcedblastbrickBlock());
	public static final RegistryObject<Block> BLASTFURNANCEMACHINE = REGISTRY.register("blastfurnancemachine", () -> new BlastfurnancemachineBlock());
	public static final RegistryObject<Block> ENGINEERSWORKBENCH = REGISTRY.register("engineersworkbench", () -> new EngineersworkbenchBlock());
	public static final RegistryObject<Block> WATERTURBINEMACHINE = REGISTRY.register("waterturbinemachine", () -> new WaterturbinemachineBlock());
	public static final RegistryObject<Block> CRUSHERMACHINE = REGISTRY.register("crushermachine", () -> new CrushermachineBlock());
	public static final RegistryObject<Block> T_1_WIRE = REGISTRY.register("t_1_wire", () -> new T1WireBlock());
	public static final RegistryObject<Block> CABLE_TT_1 = REGISTRY.register("cable_tt_1", () -> new CableTT1Block());
	public static final RegistryObject<Block> CABLE_JUNCTION_T_1 = REGISTRY.register("cable_junction_t_1", () -> new CableJunctionT1Block());
	public static final RegistryObject<Block> CABLE_ANGLE_T_1 = REGISTRY.register("cable_angle_t_1", () -> new CableAngleT1Block());
	public static final RegistryObject<Block> ENGINEERS_WORK_BENCH_SIDE = REGISTRY.register("engineers_work_bench_side", () -> new EngineersWorkBenchSideBlock());
	public static final RegistryObject<Block> ENGINEERS_WORK_BENCH_TOP = REGISTRY.register("engineers_work_bench_top", () -> new EngineersWorkBenchTopBlock());
	public static final RegistryObject<Block> ENGINEERS_WORK_BENCH_TOP_SIDE = REGISTRY.register("engineers_work_bench_top_side", () -> new EngineersWorkBenchTopSideBlock());
	public static final RegistryObject<Block> CABLE_T_UP_T_1 = REGISTRY.register("cable_t_up_t_1", () -> new CableTUpT1Block());
	public static final RegistryObject<Block> CABLE_T_DOWN_T_1 = REGISTRY.register("cable_t_down_t_1", () -> new CableTDownT1Block());
	public static final RegistryObject<Block> CABLE_T_UPAND_DOWN_T_1 = REGISTRY.register("cable_t_upand_down_t_1", () -> new CableTUpandDownT1Block());
	public static final RegistryObject<Block> CABLE_JUNCTION_UP_T_1 = REGISTRY.register("cable_junction_up_t_1", () -> new CableJunctionUpT1Block());
	public static final RegistryObject<Block> CABLE_JUNCTION_DOWN_T_1 = REGISTRY.register("cable_junction_down_t_1", () -> new CableJunctionDownT1Block());
	public static final RegistryObject<Block> CABLE_JUNCTION_UPAND_DOWN_T_1 = REGISTRY.register("cable_junction_upand_down_t_1", () -> new CableJunctionUpandDownT1Block());
	public static final RegistryObject<Block> BASECABLE_T_1 = REGISTRY.register("basecable_t_1", () -> new BasecableT1Block());
	public static final RegistryObject<Block> CABLEHALF_T_1 = REGISTRY.register("cablehalf_t_1", () -> new CablehalfT1Block());
	public static final RegistryObject<Block> BASEWIRECON_2ANGLE = REGISTRY.register("basewirecon_2angle", () -> new Basewirecon2angleBlock());
	public static final RegistryObject<Block> BASEWIRECON_2ANGLEDOWN = REGISTRY.register("basewirecon_2angledown", () -> new Basewirecon2angledownBlock());
	public static final RegistryObject<Block> BASEWIRECON_2ANGLEUP = REGISTRY.register("basewirecon_2angleup", () -> new Basewirecon2angleupBlock());
	public static final RegistryObject<Block> BASEWIRECON_3 = REGISTRY.register("basewirecon_3", () -> new Basewirecon3Block());
	public static final RegistryObject<Block> BASEWIRECON_3DOWN = REGISTRY.register("basewirecon_3down", () -> new Basewirecon3downBlock());
	public static final RegistryObject<Block> BASEWIRECON_3DOWNANDUP = REGISTRY.register("basewirecon_3downandup", () -> new Basewirecon3downandupBlock());
	public static final RegistryObject<Block> BASEWIRECON_3DOWNANGLE = REGISTRY.register("basewirecon_3downangle", () -> new Basewirecon3downangleBlock());
	public static final RegistryObject<Block> BASEWIRECON_3UP = REGISTRY.register("basewirecon_3up", () -> new Basewirecon3upBlock());
	public static final RegistryObject<Block> BASEWIRECON_3UPANGLE = REGISTRY.register("basewirecon_3upangle", () -> new Basewirecon3upangleBlock());
	public static final RegistryObject<Block> BASEWIRECON_4DOWN = REGISTRY.register("basewirecon_4down", () -> new Basewirecon4downBlock());
	public static final RegistryObject<Block> BASEWIRECON_4UP = REGISTRY.register("basewirecon_4up", () -> new Basewirecon4upBlock());
	public static final RegistryObject<Block> BASEWIRECON_4UPANDDOWN = REGISTRY.register("basewirecon_4upanddown", () -> new Basewirecon4upanddownBlock());
	public static final RegistryObject<Block> BASEWIRECON_4UPANDDOWNSTRAIGHT = REGISTRY.register("basewirecon_4upanddownstraight", () -> new Basewirecon4upanddownstraightBlock());
	public static final RegistryObject<Block> BASEWIRECON_5DOWN = REGISTRY.register("basewirecon_5down", () -> new Basewirecon5downBlock());
	public static final RegistryObject<Block> BASEWIRECON_5MAIN = REGISTRY.register("basewirecon_5main", () -> new Basewirecon5mainBlock());
	public static final RegistryObject<Block> SOLAR_PANEL_T_1 = REGISTRY.register("solar_panel_t_1", () -> new SolarPanelT1Block());
	public static final RegistryObject<Block> SOLAR_PANELR = REGISTRY.register("solar_panelr", () -> new SolarPanelrBlock());
	public static final RegistryObject<Block> SOLARPANELTOP = REGISTRY.register("solarpaneltop", () -> new SolarpaneltopBlock());
	public static final RegistryObject<Block> SOLARPANELTOPR = REGISTRY.register("solarpaneltopr", () -> new SolarpaneltoprBlock());
	public static final RegistryObject<Block> EXTRUSION_MACHINE = REGISTRY.register("extrusion_machine", () -> new ExtrusionMachineBlock());
	public static final RegistryObject<Block> ENERGY_STORAGE_T_1 = REGISTRY.register("energy_storage_t_1", () -> new EnergyStorageT1Block());
	public static final RegistryObject<Block> BASEPIPE = REGISTRY.register("basepipe", () -> new BasepipeBlock());
	public static final RegistryObject<Block> PIPEANGLE = REGISTRY.register("pipeangle", () -> new PipeangleBlock());
	public static final RegistryObject<Block> PIPEANGLEDOWN = REGISTRY.register("pipeangledown", () -> new PipeangledownBlock());
	public static final RegistryObject<Block> PIPEANLGEUP = REGISTRY.register("pipeanlgeup", () -> new PipeanlgeupBlock());
	public static final RegistryObject<Block> PIPEDOWNANGLE = REGISTRY.register("pipedownangle", () -> new PipedownangleBlock());
	public static final RegistryObject<Block> PIPEHALF = REGISTRY.register("pipehalf", () -> new PipehalfBlock());
	public static final RegistryObject<Block> PIPEJUNCTION = REGISTRY.register("pipejunction", () -> new PipejunctionBlock());
	public static final RegistryObject<Block> PIPEJUNCTIONDOWN = REGISTRY.register("pipejunctiondown", () -> new PipejunctiondownBlock());
	public static final RegistryObject<Block> PIPEJUNCTIONDOWN_2 = REGISTRY.register("pipejunctiondown_2", () -> new Pipejunctiondown2Block());
	public static final RegistryObject<Block> PIPEJUNCTIONMAIN = REGISTRY.register("pipejunctionmain", () -> new PipejunctionmainBlock());
	public static final RegistryObject<Block> PIPEJUNCTIONUP = REGISTRY.register("pipejunctionup", () -> new PipejunctionupBlock());
	public static final RegistryObject<Block> PIPEJUNCTIONUP_2 = REGISTRY.register("pipejunctionup_2", () -> new Pipejunctionup2Block());
	public static final RegistryObject<Block> PIPEJUNCTIONUPANDDOWN = REGISTRY.register("pipejunctionupanddown", () -> new PipejunctionupanddownBlock());
	public static final RegistryObject<Block> PIPEJUNCTIONUPANDDOWN_2 = REGISTRY.register("pipejunctionupanddown_2", () -> new Pipejunctionupanddown2Block());
	public static final RegistryObject<Block> PIPEJUNCTIONUPANDDOWNSTRAIGHT = REGISTRY.register("pipejunctionupanddownstraight", () -> new PipejunctionupanddownstraightBlock());
	public static final RegistryObject<Block> PIPESTRAIGHT = REGISTRY.register("pipestraight", () -> new PipestraightBlock());
	public static final RegistryObject<Block> PIPET = REGISTRY.register("pipet", () -> new PipetBlock());
	public static final RegistryObject<Block> PIPETDOWN = REGISTRY.register("pipetdown", () -> new PipetdownBlock());
	public static final RegistryObject<Block> PIPETDOWNANDUP = REGISTRY.register("pipetdownandup", () -> new PipetdownandupBlock());
	public static final RegistryObject<Block> PIPEUP = REGISTRY.register("pipeup", () -> new PipeupBlock());
	public static final RegistryObject<Block> PIPEUPANGLE = REGISTRY.register("pipeupangle", () -> new PipeupangleBlock());
	public static final RegistryObject<Block> TANK = REGISTRY.register("tank", () -> new TankBlock());
	public static final RegistryObject<Block> TANKFULL_1 = REGISTRY.register("tankfull_1", () -> new Tankfull1Block());
	public static final RegistryObject<Block> TANKFULL_2 = REGISTRY.register("tankfull_2", () -> new Tankfull2Block());
	public static final RegistryObject<Block> TANKFULL_3 = REGISTRY.register("tankfull_3", () -> new Tankfull3Block());
	public static final RegistryObject<Block> TANKFULL_4 = REGISTRY.register("tankfull_4", () -> new Tankfull4Block());
	public static final RegistryObject<Block> TANKFULL_5 = REGISTRY.register("tankfull_5", () -> new Tankfull5Block());
	public static final RegistryObject<Block> TANKFULL_6 = REGISTRY.register("tankfull_6", () -> new Tankfull6Block());
	public static final RegistryObject<Block> TANKFULL_7 = REGISTRY.register("tankfull_7", () -> new Tankfull7Block());
	public static final RegistryObject<Block> TANKFULL_8 = REGISTRY.register("tankfull_8", () -> new Tankfull8Block());
	public static final RegistryObject<Block> TANKFULL_9 = REGISTRY.register("tankfull_9", () -> new Tankfull9Block());
	public static final RegistryObject<Block> TANKFULL_10 = REGISTRY.register("tankfull_10", () -> new Tankfull10Block());
	public static final RegistryObject<Block> TANKFULL_11 = REGISTRY.register("tankfull_11", () -> new Tankfull11Block());
	public static final RegistryObject<Block> TANKFULL_12 = REGISTRY.register("tankfull_12", () -> new Tankfull12Block());
	public static final RegistryObject<Block> TANKFULL_13 = REGISTRY.register("tankfull_13", () -> new Tankfull13Block());
	public static final RegistryObject<Block> TANKFULL_14 = REGISTRY.register("tankfull_14", () -> new Tankfull14Block());
	public static final RegistryObject<Block> OIL = REGISTRY.register("oil", () -> new ElectronicsoilBlock());
	public static final RegistryObject<Block> MANUAL_FLUID_PUMP = REGISTRY.register("manual_fluid_pump", () -> new ManualFluidPumpBlock());
	public static final RegistryObject<Block> MANUAL_FLUID_PUMPDOWN_2 = REGISTRY.register("manual_fluid_pumpdown_2", () -> new ManualFluidPumpdown2Block());
	public static final RegistryObject<Block> MANUAL_FLUID_PUMP_3 = REGISTRY.register("manual_fluid_pump_3", () -> new ManualFluidPump3Block());
	public static final RegistryObject<Block> MANUAL_FLUID_PUMP_4 = REGISTRY.register("manual_fluid_pump_4", () -> new ManualFluidPump4Block());
	public static final RegistryObject<Block> MANUAL_FLUID_PUMP_5 = REGISTRY.register("manual_fluid_pump_5", () -> new ManualFluidPump5Block());
	public static final RegistryObject<Block> TANKFULLHALF_1 = REGISTRY.register("tankfullhalf_1", () -> new Tankfullhalf1Block());
	public static final RegistryObject<Block> BAUXITE_ORE = REGISTRY.register("bauxite_ore", () -> new BauxiteOreBlock());
	public static final RegistryObject<Block> BAUXITE_BLOCK = REGISTRY.register("bauxite_block", () -> new BauxiteBlockBlock());
	public static final RegistryObject<Block> BRINE = REGISTRY.register("brine", () -> new BrineBlock());
	public static final RegistryObject<Block> ROCK_SALT = REGISTRY.register("rock_salt", () -> new RockSaltBlock());
	public static final RegistryObject<Block> CHLORINE_GAS = REGISTRY.register("chlorine_gas", () -> new ChlorineGasBlock());
	public static final RegistryObject<Block> HYDROGEN_GAS = REGISTRY.register("hydrogen_gas", () -> new HydrogenGasBlock());
	public static final RegistryObject<Block> COAL_GENERATOR_MACHINE = REGISTRY.register("coal_generator_machine", () -> new CoalGeneratorMachineBlock());
	public static final RegistryObject<Block> QUARRY_T_1 = REGISTRY.register("quarry_t_1", () -> new QuarryT1Block());
	public static final RegistryObject<Block> COOLANTT_1 = REGISTRY.register("coolantt_1", () -> new Coolantt1Block());
	public static final RegistryObject<Block> REFINED_OIL = REGISTRY.register("refined_oil", () -> new RefinedOilBlock());
	public static final RegistryObject<Block> REFINERY_T_1 = REGISTRY.register("refinery_t_1", () -> new RefineryT1Block());
}
