on:
  push:
    branches:
      - dev-1.19.4

permissions:
  contents: write
  pull-requests: write

name: release-please

jobs:
  release-please:
    runs-on: ubuntu-latest
    steps:
      - uses: google-github-actions/release-please-action@v3
        with:
          version-file: https://github.com/SirStig/Elec_tronics/blob/dev-1.19.4/version.txt
          release-type: java
          package-name: release-please-action
          bump-minor-pre-major: true
          bump-patch-for-minor-pre-major: true
